insert into fornecedores (nome) values ('Torphy, Hintz and Johnson');
insert into fornecedores (nome) values ('Vandervort, Rau and Towne');
insert into fornecedores (nome) values ('Bechtelar LLC');
insert into fornecedores (nome) values ('Nolan Group');
insert into fornecedores (nome) values ('Reilly-Will');
insert into fornecedores (nome) values ('Reinger Group');
insert into fornecedores (nome) values ('Roob, Nicolas and Keeling');
insert into fornecedores (nome) values ('Ruecker, Schamberger and Gleichner');
insert into fornecedores (nome) values ('Hagenes, Hagenes and Ledner');
insert into fornecedores (nome) values ('Marks-Boyle');
insert into fornecedores (nome) values ('Dickinson and Sons');
insert into fornecedores (nome) values ('Orn Inc');
insert into fornecedores (nome) values ('Hauck-Rosenbaum');
insert into fornecedores (nome) values ('McLaughlin Inc');
insert into fornecedores (nome) values ('Hayes and Sons');
insert into fornecedores (nome) values ('Harvey, Abshire and Herman');
insert into fornecedores (nome) values ('Kovacek Group');
insert into fornecedores (nome) values ('Muller-Abshire');
insert into fornecedores (nome) values ('Jacobs LLC');
insert into fornecedores (nome) values ('Toy Group');
insert into fornecedores (nome) values ('Powlowski, Barton and Keeling');
insert into fornecedores (nome) values ('Franecki and Sons');
insert into fornecedores (nome) values ('Champlin LLC');
insert into fornecedores (nome) values ('Champlin Inc');
insert into fornecedores (nome) values ('Jones-Von');
insert into fornecedores (nome) values ('Sipes Inc');
insert into fornecedores (nome) values ('McLaughlin Inc');
insert into fornecedores (nome) values ('Konopelski-Mueller');
insert into fornecedores (nome) values ('MacGyver Group');
insert into fornecedores (nome) values ('Langosh, Kirlin and Batz');
insert into fornecedores (nome) values ('Kub Group');
insert into fornecedores (nome) values ('Lesch LLC');
insert into fornecedores (nome) values ('Zieme and Sons');
insert into fornecedores (nome) values ('Gusikowski-Waelchi');
insert into fornecedores (nome) values ('Gutmann, Miller and Windler');
insert into fornecedores (nome) values ('Bernhard-Johnson');
insert into fornecedores (nome) values ('Monahan-Waters');
insert into fornecedores (nome) values ('Littel Group');
insert into fornecedores (nome) values ('Corkery, Harber and Bayer');
insert into fornecedores (nome) values ('Zboncak Group');
insert into fornecedores (nome) values ('Gleason, Daniel and Jacobi');
insert into fornecedores (nome) values ('Crooks, Pfannerstill and Lakin');
insert into fornecedores (nome) values ('Yost, Kerluke and Lehner');
insert into fornecedores (nome) values ('Rath Group');
insert into fornecedores (nome) values ('Zulauf-Hickle');
insert into fornecedores (nome) values ('Abernathy Inc');
insert into fornecedores (nome) values ('Padberg, Rath and McKenzie');
insert into fornecedores (nome) values ('Crona, Bashirian and Wunsch');
insert into fornecedores (nome) values ('Schmitt-Olson');
insert into fornecedores (nome) values ('Cummings-Hammes');
insert into fornecedores (nome) values ('Gulgowski-Trantow');
insert into fornecedores (nome) values ('Berge, Abshire and Emard');
insert into fornecedores (nome) values ('Braun LLC');
insert into fornecedores (nome) values ('Wilkinson Group');
insert into fornecedores (nome) values ('Upton Inc');
insert into fornecedores (nome) values ('Kohler-Wunsch');
insert into fornecedores (nome) values ('Effertz, Dooley and Hayes');
insert into fornecedores (nome) values ('Bosco and Sons');
insert into fornecedores (nome) values ('Zieme Inc');
insert into fornecedores (nome) values ('Mann-Miller');
insert into fornecedores (nome) values ('Hahn-Rowe');
insert into fornecedores (nome) values ('Considine-Abshire');
insert into fornecedores (nome) values ('Satterfield, Effertz and Carter');
insert into fornecedores (nome) values ('Gislason-Denesik');
insert into fornecedores (nome) values ('Becker-Zemlak');
insert into fornecedores (nome) values ('Berge-Altenwerth');
insert into fornecedores (nome) values ('Kreiger Group');
insert into fornecedores (nome) values ('Tromp and Sons');
insert into fornecedores (nome) values ('Dare and Sons');
insert into fornecedores (nome) values ('Pollich and Sons');
insert into fornecedores (nome) values ('Hickle-Predovic');
insert into fornecedores (nome) values ('Hills Group');
insert into fornecedores (nome) values ('Hudson, Macejkovic and Ernser');
insert into fornecedores (nome) values ('Von-Krajcik');
insert into fornecedores (nome) values ('Schmitt and Sons');
insert into fornecedores (nome) values ('Wintheiser, Padberg and Schmeler');
insert into fornecedores (nome) values ('Towne Group');
insert into fornecedores (nome) values ('Gerlach, Gerhold and Muller');
insert into fornecedores (nome) values ('Beer-Turcotte');
insert into fornecedores (nome) values ('Gleason, Beier and Nicolas');
insert into fornecedores (nome) values ('Homenick LLC');
insert into fornecedores (nome) values ('Goyette Inc');
insert into fornecedores (nome) values ('Moen, Rodriguez and Kirlin');
insert into fornecedores (nome) values ('Stiedemann LLC');
insert into fornecedores (nome) values ('Vandervort LLC');
insert into fornecedores (nome) values ('Jenkins Inc');
insert into fornecedores (nome) values ('Raynor Inc');
insert into fornecedores (nome) values ('Ryan, Mohr and Maggio');
insert into fornecedores (nome) values ('Schaden-Wilkinson');
insert into fornecedores (nome) values ('Herzog, Kutch and Balistreri');
insert into fornecedores (nome) values ('Fay Group');
insert into fornecedores (nome) values ('Blick-Dare');
insert into fornecedores (nome) values ('Wisozk, MacGyver and Senger');
insert into fornecedores (nome) values ('Crona, D''Amore and Schroeder');
insert into fornecedores (nome) values ('Rolfson, Stiedemann and Mayert');
insert into fornecedores (nome) values ('Macejkovic Inc');
insert into fornecedores (nome) values ('Howe-Walker');
insert into fornecedores (nome) values ('Senger, Kiehn and Hoeger');
insert into fornecedores (nome) values ('Hills-Sawayn');
insert into fornecedores (nome) values ('Hansen-McKenzie');
insert into fornecedores (nome) values ('Boyle Inc');
insert into fornecedores (nome) values ('Gleichner-Bechtelar');
insert into fornecedores (nome) values ('Osinski Inc');
insert into fornecedores (nome) values ('Schowalter-Bernhard');
insert into fornecedores (nome) values ('Wolf-Kohler');
insert into fornecedores (nome) values ('Nicolas-Abernathy');
insert into fornecedores (nome) values ('Deckow, Gleason and Davis');
insert into fornecedores (nome) values ('Little-Huels');
insert into fornecedores (nome) values ('O''Connell and Sons');
insert into fornecedores (nome) values ('Feil LLC');
insert into fornecedores (nome) values ('Rutherford, Cassin and Larson');
insert into fornecedores (nome) values ('Waelchi Group');
insert into fornecedores (nome) values ('Bartoletti LLC');
insert into fornecedores (nome) values ('Casper, Tromp and Kuhic');
insert into fornecedores (nome) values ('Donnelly, Volkman and Koelpin');
insert into fornecedores (nome) values ('Reichert Inc');
insert into fornecedores (nome) values ('Gleason, Emard and Conn');
insert into fornecedores (nome) values ('Zieme Inc');
insert into fornecedores (nome) values ('Lindgren LLC');
insert into fornecedores (nome) values ('Braun LLC');
insert into fornecedores (nome) values ('Rodriguez Inc');
insert into fornecedores (nome) values ('Kuvalis-Johnson');
insert into fornecedores (nome) values ('Effertz-Hyatt');
insert into fornecedores (nome) values ('Hermann Group');
insert into fornecedores (nome) values ('Zieme, Grady and Kautzer');
insert into fornecedores (nome) values ('Kerluke LLC');
insert into fornecedores (nome) values ('Mraz Group');
insert into fornecedores (nome) values ('Leuschke, Bosco and Hills');
insert into fornecedores (nome) values ('Ratke Group');
insert into fornecedores (nome) values ('Leffler-Bartell');
insert into fornecedores (nome) values ('Turcotte, Kuphal and Hickle');
insert into fornecedores (nome) values ('Roob Inc');
insert into fornecedores (nome) values ('Muller-Weimann');
insert into fornecedores (nome) values ('Walker-Barton');
insert into fornecedores (nome) values ('Ondricka Group');
insert into fornecedores (nome) values ('Dach, Klein and Johnson');
insert into fornecedores (nome) values ('Schaefer and Sons');
insert into fornecedores (nome) values ('Smitham-Swaniawski');
insert into fornecedores (nome) values ('Rodriguez, Hilll and Lesch');
insert into fornecedores (nome) values ('Fadel-Crist');
insert into fornecedores (nome) values ('McDermott-Homenick');
insert into fornecedores (nome) values ('Buckridge-Hoeger');
insert into fornecedores (nome) values ('Tromp and Sons');
insert into fornecedores (nome) values ('Ferry, Kemmer and Graham');
insert into fornecedores (nome) values ('Gerlach, Davis and Gutmann');
insert into fornecedores (nome) values ('Lebsack-Yundt');
insert into fornecedores (nome) values ('Keeling LLC');
insert into fornecedores (nome) values ('Block-Barrows');
insert into fornecedores (nome) values ('Rippin, Schmidt and Waters');
insert into fornecedores (nome) values ('Hettinger-Marquardt');
insert into fornecedores (nome) values ('Pollich-Hirthe');
insert into fornecedores (nome) values ('Marvin-Veum');
insert into fornecedores (nome) values ('Keebler, Brakus and Schaefer');
insert into fornecedores (nome) values ('Kautzer-Prohaska');
insert into fornecedores (nome) values ('Shanahan Group');
insert into fornecedores (nome) values ('Sawayn LLC');
insert into fornecedores (nome) values ('Barrows LLC');
insert into fornecedores (nome) values ('Senger Group');
insert into fornecedores (nome) values ('Anderson, Gutkowski and McClure');
insert into fornecedores (nome) values ('Crona, Klocko and Nikolaus');
insert into fornecedores (nome) values ('Moore Inc');
insert into fornecedores (nome) values ('Kuhlman, Casper and Romaguera');
insert into fornecedores (nome) values ('Goyette-Crona');
insert into fornecedores (nome) values ('Kuhic Group');
insert into fornecedores (nome) values ('Jenkins, Ortiz and McClure');
insert into fornecedores (nome) values ('Bailey-Abernathy');
insert into fornecedores (nome) values ('Koepp-Collier');
insert into fornecedores (nome) values ('Effertz and Sons');
insert into fornecedores (nome) values ('Goldner, Gusikowski and Reichert');
insert into fornecedores (nome) values ('Koepp-Schmidt');
insert into fornecedores (nome) values ('Pollich, Stark and Mante');
insert into fornecedores (nome) values ('Watsica-Gleichner');
insert into fornecedores (nome) values ('Hettinger, Bashirian and Dare');
insert into fornecedores (nome) values ('Hickle, Price and Fritsch');
insert into fornecedores (nome) values ('Stoltenberg-Harris');
insert into fornecedores (nome) values ('Armstrong Inc');
insert into fornecedores (nome) values ('Prohaska-Brown');
insert into fornecedores (nome) values ('Stokes LLC');
insert into fornecedores (nome) values ('Powlowski-Reichel');
insert into fornecedores (nome) values ('Murray Inc');
insert into fornecedores (nome) values ('Steuber, Jacobson and Howe');
insert into fornecedores (nome) values ('Heidenreich and Sons');
insert into fornecedores (nome) values ('Bins, Goodwin and Keeling');
insert into fornecedores (nome) values ('Shanahan-West');
insert into fornecedores (nome) values ('Buckridge-Welch');
insert into fornecedores (nome) values ('Sanford LLC');
insert into fornecedores (nome) values ('Ortiz and Sons');
insert into fornecedores (nome) values ('Morar, Fritsch and Nitzsche');
insert into fornecedores (nome) values ('O''Connell, Adams and Mayert');
insert into fornecedores (nome) values ('Satterfield and Sons');
insert into fornecedores (nome) values ('Medhurst-Weimann');
insert into fornecedores (nome) values ('Prohaska-Yundt');
insert into fornecedores (nome) values ('Mayert LLC');
insert into fornecedores (nome) values ('Labadie Inc');
insert into fornecedores (nome) values ('Johnston, Mueller and Hodkiewicz');
insert into fornecedores (nome) values ('Wehner LLC');
insert into fornecedores (nome) values ('Wolff-Cronin');
insert into fornecedores (nome) values ('Beier-Wolf');
insert into fornecedores (nome) values ('Reichel Group');
insert into fornecedores (nome) values ('Ferry Inc');
insert into fornecedores (nome) values ('Sawayn-Aufderhar');
insert into fornecedores (nome) values ('Hermann-Reynolds');
insert into fornecedores (nome) values ('Renner-Moore');
insert into fornecedores (nome) values ('Bogan, Sanford and Veum');
insert into fornecedores (nome) values ('Murazik Inc');
insert into fornecedores (nome) values ('Harber-Hane');
insert into fornecedores (nome) values ('Smith-Lebsack');
insert into fornecedores (nome) values ('Kassulke Inc');
insert into fornecedores (nome) values ('Kunde Inc');
insert into fornecedores (nome) values ('Pollich, Roberts and Yost');
insert into fornecedores (nome) values ('Carter, Beatty and Donnelly');
insert into fornecedores (nome) values ('Jones, Kunze and Pacocha');
insert into fornecedores (nome) values ('Dietrich-Hahn');
insert into fornecedores (nome) values ('Grant-Wuckert');
insert into fornecedores (nome) values ('Roob-Dicki');
insert into fornecedores (nome) values ('Haag Inc');
insert into fornecedores (nome) values ('Mohr LLC');
insert into fornecedores (nome) values ('Hirthe LLC');
insert into fornecedores (nome) values ('Ruecker, Tromp and Wiza');
insert into fornecedores (nome) values ('Ritchie Group');
insert into fornecedores (nome) values ('Parisian LLC');
insert into fornecedores (nome) values ('Batz, Klocko and Gulgowski');
insert into fornecedores (nome) values ('Borer, Anderson and O''Conner');
insert into fornecedores (nome) values ('Price, Prohaska and VonRueden');
insert into fornecedores (nome) values ('Nienow LLC');
insert into fornecedores (nome) values ('Kirlin Inc');
insert into fornecedores (nome) values ('Prohaska-Fadel');
insert into fornecedores (nome) values ('Brown-Schroeder');
insert into fornecedores (nome) values ('Gottlieb LLC');
insert into fornecedores (nome) values ('Mitchell-McGlynn');
insert into fornecedores (nome) values ('Gerlach and Sons');
insert into fornecedores (nome) values ('Stokes, Okuneva and Reichert');
insert into fornecedores (nome) values ('Schulist-Grady');
insert into fornecedores (nome) values ('Romaguera, Raynor and Bahringer');
insert into fornecedores (nome) values ('Wisozk, Blanda and Powlowski');
insert into fornecedores (nome) values ('Yundt-Brakus');
insert into fornecedores (nome) values ('Maggio, Cormier and Yost');
insert into fornecedores (nome) values ('Ziemann Group');
insert into fornecedores (nome) values ('Schoen, Wehner and Schoen');
insert into fornecedores (nome) values ('Hilll, Rogahn and Smitham');
insert into fornecedores (nome) values ('Mills, Green and Murazik');
insert into fornecedores (nome) values ('Cremin LLC');
insert into fornecedores (nome) values ('Emmerich LLC');
insert into fornecedores (nome) values ('Nicolas-Hane');
insert into fornecedores (nome) values ('Block, Stamm and Heidenreich');
insert into fornecedores (nome) values ('Grant Group');
insert into fornecedores (nome) values ('Wolff Inc');
insert into fornecedores (nome) values ('Conroy, Wuckert and Armstrong');
insert into fornecedores (nome) values ('Lockman, Barrows and Morissette');
insert into fornecedores (nome) values ('Bauch LLC');
insert into fornecedores (nome) values ('Gulgowski Group');
insert into fornecedores (nome) values ('Kertzmann-Lindgren');
insert into fornecedores (nome) values ('Hettinger-Metz');
insert into fornecedores (nome) values ('Harris-Corwin');
insert into fornecedores (nome) values ('Jacobs Inc');
insert into fornecedores (nome) values ('Wisoky, Reilly and Gottlieb');
insert into fornecedores (nome) values ('Bartoletti, Marks and McLaughlin');
insert into fornecedores (nome) values ('Beatty Group');
insert into fornecedores (nome) values ('Auer-Heaney');
insert into fornecedores (nome) values ('Lueilwitz and Sons');
insert into fornecedores (nome) values ('Greenfelder, Sporer and Koepp');
insert into fornecedores (nome) values ('Bogisich-Jacobson');
insert into fornecedores (nome) values ('Streich, Kilback and Block');
insert into fornecedores (nome) values ('O''Kon LLC');
insert into fornecedores (nome) values ('Schimmel, Ankunding and Towne');
insert into fornecedores (nome) values ('Lesch, Casper and Senger');
insert into fornecedores (nome) values ('Stamm-Cole');
insert into fornecedores (nome) values ('Jast-Funk');
insert into fornecedores (nome) values ('Reichert-Kautzer');
insert into fornecedores (nome) values ('Spencer, Grady and McKenzie');
insert into fornecedores (nome) values ('Harvey and Sons');
insert into fornecedores (nome) values ('Mayert, Koepp and Swift');
insert into fornecedores (nome) values ('Satterfield, Raynor and Mosciski');
insert into fornecedores (nome) values ('Mayer-Bernhard');
insert into fornecedores (nome) values ('Hegmann, Schuppe and Dibbert');
insert into fornecedores (nome) values ('Little, Schmitt and Bradtke');
insert into fornecedores (nome) values ('Ernser-Lindgren');
insert into fornecedores (nome) values ('Emmerich LLC');
insert into fornecedores (nome) values ('Bruen-Weimann');
insert into fornecedores (nome) values ('Okuneva-Green');
insert into fornecedores (nome) values ('Howe-Rutherford');
insert into fornecedores (nome) values ('Abbott, Prohaska and Williamson');
insert into fornecedores (nome) values ('Kiehn-Spinka');
insert into fornecedores (nome) values ('Prohaska-Hilll');
insert into fornecedores (nome) values ('Littel, Schroeder and Feil');
insert into fornecedores (nome) values ('Hilll, Lang and Hansen');
insert into fornecedores (nome) values ('Wuckert LLC');
insert into fornecedores (nome) values ('Deckow, Schiller and Walker');
insert into fornecedores (nome) values ('Wilkinson-Von');
insert into fornecedores (nome) values ('Raynor, Bauch and Jacobi');
insert into fornecedores (nome) values ('Ankunding-O''Keefe');
insert into fornecedores (nome) values ('Zieme-Rau');
insert into fornecedores (nome) values ('Trantow, Howe and Sporer');
insert into fornecedores (nome) values ('Padberg Group');
insert into fornecedores (nome) values ('Koss, Kris and Boyle');
insert into fornecedores (nome) values ('Dibbert LLC');
insert into fornecedores (nome) values ('Leuschke-Moore');
insert into fornecedores (nome) values ('Lakin LLC');
insert into fornecedores (nome) values ('Hessel Group');
insert into fornecedores (nome) values ('Bartoletti, Harber and Morissette');
insert into fornecedores (nome) values ('Douglas Inc');
insert into fornecedores (nome) values ('Hirthe Group');
insert into fornecedores (nome) values ('Kautzer-Leuschke');
insert into fornecedores (nome) values ('Morissette, Gerlach and Sanford');
insert into fornecedores (nome) values ('Russel, Lang and Bauch');
insert into fornecedores (nome) values ('Bauch-Kuphal');
insert into fornecedores (nome) values ('Emard Inc');
insert into fornecedores (nome) values ('Miller, Zulauf and Morar');
insert into fornecedores (nome) values ('McCullough, White and Muller');
insert into fornecedores (nome) values ('Padberg-Goodwin');
insert into fornecedores (nome) values ('Marks, Satterfield and Fay');
insert into fornecedores (nome) values ('Smith, Williamson and Cassin');
insert into fornecedores (nome) values ('Roob Group');
insert into fornecedores (nome) values ('Schmeler-Kuvalis');
insert into fornecedores (nome) values ('Beahan Inc');
insert into fornecedores (nome) values ('Tillman, Abbott and Lemke');
insert into fornecedores (nome) values ('Mohr Inc');
insert into fornecedores (nome) values ('Nikolaus, Kozey and Mraz');
insert into fornecedores (nome) values ('Mills Group');
insert into fornecedores (nome) values ('Murphy-Johnston');
insert into fornecedores (nome) values ('Heller-Mueller');
insert into fornecedores (nome) values ('Windler, Turcotte and Schamberger');
insert into fornecedores (nome) values ('Grant Group');
insert into fornecedores (nome) values ('Brekke-Graham');
insert into fornecedores (nome) values ('Collins-Rice');
insert into fornecedores (nome) values ('Marquardt-Gerlach');
insert into fornecedores (nome) values ('Ledner, Haley and Abbott');
insert into fornecedores (nome) values ('Trantow-Kozey');
insert into fornecedores (nome) values ('Lubowitz-Krajcik');
insert into fornecedores (nome) values ('Kunze, Collier and Stokes');
insert into fornecedores (nome) values ('Waelchi-Hane');
insert into fornecedores (nome) values ('Schuppe-Bartoletti');
insert into fornecedores (nome) values ('Lehner, Gislason and Quigley');
insert into fornecedores (nome) values ('Schiller-Bosco');
insert into fornecedores (nome) values ('Rohan, Hegmann and Senger');
insert into fornecedores (nome) values ('Runte-Doyle');
insert into fornecedores (nome) values ('Hartmann-Hammes');
insert into fornecedores (nome) values ('Auer-Gislason');
insert into fornecedores (nome) values ('Corkery, White and Dickinson');
insert into fornecedores (nome) values ('Hoppe-Rohan');
insert into fornecedores (nome) values ('Lowe LLC');
insert into fornecedores (nome) values ('Haag-Rippin');
insert into fornecedores (nome) values ('Adams-Heller');
insert into fornecedores (nome) values ('Parker, Kub and King');
insert into fornecedores (nome) values ('Gulgowski, Dickinson and Reichert');
insert into fornecedores (nome) values ('Hoeger and Sons');
insert into fornecedores (nome) values ('Luettgen LLC');
insert into fornecedores (nome) values ('Williamson-Dare');
insert into fornecedores (nome) values ('Douglas, Dicki and Reinger');
insert into fornecedores (nome) values ('Dietrich Group');
insert into fornecedores (nome) values ('Corwin, Bins and Ortiz');
insert into fornecedores (nome) values ('Gleason LLC');
insert into fornecedores (nome) values ('Barton-Hickle');
insert into fornecedores (nome) values ('Leuschke-Rowe');
insert into fornecedores (nome) values ('Beer, DuBuque and Schimmel');
insert into fornecedores (nome) values ('Medhurst LLC');
insert into fornecedores (nome) values ('Rodriguez, Donnelly and Davis');
insert into fornecedores (nome) values ('Koch-Legros');
insert into fornecedores (nome) values ('Conn-Pagac');
insert into fornecedores (nome) values ('Hintz, Brakus and Jacobson');
insert into fornecedores (nome) values ('Rodriguez-Bernhard');
insert into fornecedores (nome) values ('Koelpin and Sons');
insert into fornecedores (nome) values ('Kertzmann Inc');
insert into fornecedores (nome) values ('Corwin-Murphy');
insert into fornecedores (nome) values ('Murray, Hilpert and Bechtelar');
insert into fornecedores (nome) values ('Wilkinson and Sons');
insert into fornecedores (nome) values ('Stanton Group');
insert into fornecedores (nome) values ('Hamill and Sons');
insert into fornecedores (nome) values ('Ruecker Group');
insert into fornecedores (nome) values ('Satterfield, Olson and Bechtelar');
insert into fornecedores (nome) values ('Bode, Tillman and Rempel');
insert into fornecedores (nome) values ('Thiel and Sons');
insert into fornecedores (nome) values ('Sporer-Wilkinson');
insert into fornecedores (nome) values ('Stark-Nitzsche');
insert into fornecedores (nome) values ('Kutch and Sons');
insert into fornecedores (nome) values ('Hayes, Wiegand and Gulgowski');
insert into fornecedores (nome) values ('Kutch Inc');
insert into fornecedores (nome) values ('Mayert LLC');
insert into fornecedores (nome) values ('Schumm Group');
insert into fornecedores (nome) values ('Jast, Dooley and Hand');
insert into fornecedores (nome) values ('Schmitt Inc');
insert into fornecedores (nome) values ('Feeney Inc');
insert into fornecedores (nome) values ('Doyle, Schamberger and Runolfsdottir');
insert into fornecedores (nome) values ('Parisian, Kerluke and Hessel');
insert into fornecedores (nome) values ('Goodwin, Ferry and Quitzon');
insert into fornecedores (nome) values ('Wunsch and Sons');
insert into fornecedores (nome) values ('Roberts and Sons');
insert into fornecedores (nome) values ('Kozey-Wehner');
insert into fornecedores (nome) values ('Wilderman, Gerhold and Fahey');
insert into fornecedores (nome) values ('Von, Bins and Mosciski');
insert into fornecedores (nome) values ('Schulist, McKenzie and Wolf');
insert into fornecedores (nome) values ('Gerlach-Sipes');
insert into fornecedores (nome) values ('Mills LLC');
insert into fornecedores (nome) values ('Keebler, Kuhic and Marks');
insert into fornecedores (nome) values ('Beer-Terry');
insert into fornecedores (nome) values ('Daugherty-Connelly');
insert into fornecedores (nome) values ('Ankunding, Kunze and Hand');
insert into fornecedores (nome) values ('Prosacco, Abernathy and Homenick');
insert into fornecedores (nome) values ('Purdy, Trantow and Kutch');
insert into fornecedores (nome) values ('Greenholt LLC');
insert into fornecedores (nome) values ('Fritsch and Sons');
insert into fornecedores (nome) values ('Stoltenberg Inc');
insert into fornecedores (nome) values ('Krajcik Inc');
insert into fornecedores (nome) values ('Kiehn-O''Connell');
insert into fornecedores (nome) values ('Schneider LLC');
insert into fornecedores (nome) values ('Dicki and Sons');
insert into fornecedores (nome) values ('Bernhard LLC');
insert into fornecedores (nome) values ('Hudson, Kerluke and Beier');
insert into fornecedores (nome) values ('Blick-Ernser');
insert into fornecedores (nome) values ('Bogan-Harris');
insert into fornecedores (nome) values ('Hermiston-Thiel');
insert into fornecedores (nome) values ('Osinski-Moen');
insert into fornecedores (nome) values ('Kshlerin Inc');
insert into fornecedores (nome) values ('Schimmel, Marvin and Legros');
insert into fornecedores (nome) values ('Witting Group');
insert into fornecedores (nome) values ('Lueilwitz, Bednar and McCullough');
insert into fornecedores (nome) values ('Beer-Monahan');
insert into fornecedores (nome) values ('Hessel-Ratke');
insert into fornecedores (nome) values ('Marks Group');
insert into fornecedores (nome) values ('Schamberger-Haag');
insert into fornecedores (nome) values ('Effertz and Sons');
insert into fornecedores (nome) values ('Lind, Stoltenberg and Osinski');
insert into fornecedores (nome) values ('Harber Inc');
insert into fornecedores (nome) values ('Konopelski-Quigley');
insert into fornecedores (nome) values ('Skiles, Wisoky and Emard');
insert into fornecedores (nome) values ('Davis Inc');
insert into fornecedores (nome) values ('Larson-Rath');
insert into fornecedores (nome) values ('Heathcote, Murazik and Leannon');
insert into fornecedores (nome) values ('Morar-Mertz');
insert into fornecedores (nome) values ('Prosacco-Breitenberg');
insert into fornecedores (nome) values ('Nienow, Hilll and Boyle');
insert into fornecedores (nome) values ('Kautzer-Nikolaus');
insert into fornecedores (nome) values ('Altenwerth Inc');
insert into fornecedores (nome) values ('Mueller and Sons');
insert into fornecedores (nome) values ('Powlowski-Schulist');
insert into fornecedores (nome) values ('Lind, Schuster and Goldner');
insert into fornecedores (nome) values ('Cartwright-Shanahan');
insert into fornecedores (nome) values ('Lebsack-Hills');
insert into fornecedores (nome) values ('Feest, Howe and Ullrich');
insert into fornecedores (nome) values ('Koelpin, Keeling and Powlowski');
insert into fornecedores (nome) values ('Upton Group');
insert into fornecedores (nome) values ('Fadel, Quitzon and Kling');
insert into fornecedores (nome) values ('Langosh-Wolf');
insert into fornecedores (nome) values ('Leuschke, Grady and West');
insert into fornecedores (nome) values ('Keeling, McDermott and Smith');
insert into fornecedores (nome) values ('Rutherford, Cremin and Leuschke');
insert into fornecedores (nome) values ('Kreiger-Kuhlman');
insert into fornecedores (nome) values ('Ernser, Treutel and Jast');
insert into fornecedores (nome) values ('Larson, Johnston and Krajcik');
insert into fornecedores (nome) values ('Wiegand-Champlin');
insert into fornecedores (nome) values ('Mitchell-Harber');
insert into fornecedores (nome) values ('Daugherty-Emmerich');
insert into fornecedores (nome) values ('Kautzer LLC');
insert into fornecedores (nome) values ('Kautzer Group');
insert into fornecedores (nome) values ('Haley, Berge and Cummerata');
insert into fornecedores (nome) values ('Ernser-Hintz');
insert into fornecedores (nome) values ('Bernhard-Bauch');
insert into fornecedores (nome) values ('Dietrich-Turcotte');
insert into fornecedores (nome) values ('Quigley, Stoltenberg and Howe');
insert into fornecedores (nome) values ('Wyman, Price and Herzog');
insert into fornecedores (nome) values ('Turner, Leffler and Kunde');
insert into fornecedores (nome) values ('Swaniawski Group');
insert into fornecedores (nome) values ('Bahringer-Wuckert');
insert into fornecedores (nome) values ('Johnston-Russel');
insert into fornecedores (nome) values ('Metz Inc');
insert into fornecedores (nome) values ('Dickinson, Baumbach and Bradtke');
insert into fornecedores (nome) values ('Stehr and Sons');
insert into fornecedores (nome) values ('Casper-Padberg');
insert into fornecedores (nome) values ('Windler-Dietrich');
insert into fornecedores (nome) values ('Dibbert-Moen');
insert into fornecedores (nome) values ('Hudson, O''Kon and Goldner');
insert into fornecedores (nome) values ('McDermott LLC');
insert into fornecedores (nome) values ('Wehner, Connelly and Zboncak');
insert into fornecedores (nome) values ('Pfannerstill, Shanahan and Leannon');
insert into fornecedores (nome) values ('Mueller and Sons');
insert into fornecedores (nome) values ('Heathcote, Cronin and Waters');
insert into fornecedores (nome) values ('Rodriguez, Cremin and Kuhn');
insert into fornecedores (nome) values ('Ziemann-Wunsch');
insert into fornecedores (nome) values ('Hintz-Robel');
insert into fornecedores (nome) values ('Adams, Rath and Lindgren');
insert into fornecedores (nome) values ('Rolfson-Pollich');
insert into fornecedores (nome) values ('Runte, Boehm and Kertzmann');
insert into fornecedores (nome) values ('Keeling-Russel');
insert into fornecedores (nome) values ('Effertz, Thiel and Kreiger');
insert into fornecedores (nome) values ('Lindgren, Mante and Little');
insert into fornecedores (nome) values ('Armstrong, Turcotte and Willms');
insert into fornecedores (nome) values ('Kshlerin Group');
insert into fornecedores (nome) values ('Herzog, Beahan and Barrows');
insert into fornecedores (nome) values ('Kling-Kris');
insert into fornecedores (nome) values ('Koss, Toy and O''Conner');
insert into fornecedores (nome) values ('Block, Graham and McClure');
insert into fornecedores (nome) values ('Ritchie Inc');
insert into fornecedores (nome) values ('Daugherty-Baumbach');
insert into fornecedores (nome) values ('Cormier, Waters and Johnson');
insert into fornecedores (nome) values ('Schamberger, Braun and Crist');
insert into fornecedores (nome) values ('VonRueden-Mayert');
insert into fornecedores (nome) values ('Hickle-Bauch');
insert into fornecedores (nome) values ('Bartoletti LLC');
insert into fornecedores (nome) values ('Gibson-Will');
insert into fornecedores (nome) values ('Collins, Brown and Rowe');
insert into fornecedores (nome) values ('Wiegand, Larkin and O''Connell');
insert into fornecedores (nome) values ('Abshire Inc');
insert into fornecedores (nome) values ('Weissnat and Sons');
insert into fornecedores (nome) values ('Collier and Sons');
insert into fornecedores (nome) values ('Kuhic, Abernathy and Lind');
insert into fornecedores (nome) values ('Stokes-Braun');
insert into fornecedores (nome) values ('Considine, Hilll and O''Reilly');
insert into fornecedores (nome) values ('Weber, Ruecker and Harris');
insert into fornecedores (nome) values ('Pollich-Zieme');
insert into fornecedores (nome) values ('Waters Inc');
insert into fornecedores (nome) values ('Quitzon, Wehner and Schoen');
insert into fornecedores (nome) values ('Witting, Hackett and Shanahan');
insert into fornecedores (nome) values ('Runolfsson and Sons');
insert into fornecedores (nome) values ('Sipes-Berge');
insert into fornecedores (nome) values ('Spencer, Zulauf and Barrows');
insert into fornecedores (nome) values ('Lindgren Inc');
insert into fornecedores (nome) values ('Jerde, Prosacco and Rath');
insert into fornecedores (nome) values ('Little, Willms and Breitenberg');
insert into fornecedores (nome) values ('Durgan, Halvorson and Gulgowski');
insert into fornecedores (nome) values ('Murray-Dare');
insert into fornecedores (nome) values ('Wehner LLC');
insert into fornecedores (nome) values ('Kirlin, Franecki and Cole');
insert into fornecedores (nome) values ('Rippin, Purdy and Mante');
insert into fornecedores (nome) values ('Sipes, Rutherford and Hettinger');
insert into fornecedores (nome) values ('Lesch, Rippin and Kemmer');
insert into fornecedores (nome) values ('Roberts, Bartoletti and Kohler');
insert into fornecedores (nome) values ('Emmerich-Mraz');
insert into fornecedores (nome) values ('Blick LLC');
insert into fornecedores (nome) values ('Huels, Kautzer and Runolfsdottir');
insert into fornecedores (nome) values ('Monahan, Labadie and Gislason');
insert into fornecedores (nome) values ('Little Group');
insert into fornecedores (nome) values ('Rodriguez, Weissnat and Shanahan');
insert into fornecedores (nome) values ('Veum, Tromp and Jacobs');
insert into fornecedores (nome) values ('Roberts, Cartwright and Wyman');
insert into fornecedores (nome) values ('Abernathy LLC');
insert into fornecedores (nome) values ('Hessel Inc');
insert into fornecedores (nome) values ('Abernathy-Walsh');
insert into fornecedores (nome) values ('Wisoky-Donnelly');
insert into fornecedores (nome) values ('Lubowitz, Swift and Pacocha');
insert into fornecedores (nome) values ('Schmeler-Lakin');
insert into fornecedores (nome) values ('Kiehn, Flatley and Kuhlman');
insert into fornecedores (nome) values ('Lemke-Feeney');
insert into fornecedores (nome) values ('Jerde, Kuvalis and Little');
insert into fornecedores (nome) values ('Bernhard Group');
insert into fornecedores (nome) values ('Quigley LLC');
insert into fornecedores (nome) values ('Howe-Stanton');
insert into fornecedores (nome) values ('Shields, Friesen and Lakin');
insert into fornecedores (nome) values ('Weimann, Keebler and Hansen');
insert into fornecedores (nome) values ('Barton-Gleason');
insert into fornecedores (nome) values ('Bradtke, Johnston and Anderson');
insert into fornecedores (nome) values ('Mosciski-Haag');
insert into fornecedores (nome) values ('Cronin-Kunde');
insert into fornecedores (nome) values ('Langworth-Turner');
insert into fornecedores (nome) values ('Stiedemann and Sons');
insert into fornecedores (nome) values ('Littel, Gleason and Miller');
insert into fornecedores (nome) values ('Cruickshank, Jones and Paucek');
insert into fornecedores (nome) values ('Block-Bruen');
insert into fornecedores (nome) values ('Kreiger, Satterfield and Cruickshank');
insert into fornecedores (nome) values ('Brakus LLC');
insert into fornecedores (nome) values ('Kulas-Leannon');
insert into fornecedores (nome) values ('Durgan, Grimes and Harber');
insert into fornecedores (nome) values ('Paucek-Lakin');
insert into fornecedores (nome) values ('Maggio LLC');
insert into fornecedores (nome) values ('VonRueden Group');
insert into fornecedores (nome) values ('Anderson, Homenick and Adams');
insert into fornecedores (nome) values ('Satterfield, Macejkovic and Boyle');
insert into fornecedores (nome) values ('Hessel LLC');
insert into fornecedores (nome) values ('Sipes and Sons');
insert into fornecedores (nome) values ('Schmitt LLC');
insert into fornecedores (nome) values ('Steuber LLC');
insert into fornecedores (nome) values ('Mraz LLC');
insert into fornecedores (nome) values ('Dooley, Satterfield and Walsh');
insert into fornecedores (nome) values ('Kunde-Dooley');
insert into fornecedores (nome) values ('Mraz-Bartell');
insert into fornecedores (nome) values ('Stroman-Wiza');
insert into fornecedores (nome) values ('Emard LLC');
insert into fornecedores (nome) values ('Murray Group');
insert into fornecedores (nome) values ('Turner, Hickle and Hackett');
insert into fornecedores (nome) values ('Auer Group');
insert into fornecedores (nome) values ('Boyer Inc');
insert into fornecedores (nome) values ('Ledner LLC');
insert into fornecedores (nome) values ('Greenholt, Swaniawski and O''Reilly');
insert into fornecedores (nome) values ('Veum-Tromp');
insert into fornecedores (nome) values ('Goodwin-Bode');
insert into fornecedores (nome) values ('Corkery, Breitenberg and Wolf');
insert into fornecedores (nome) values ('Kuhic-Gleason');
insert into fornecedores (nome) values ('Berge, Bruen and Johns');
insert into fornecedores (nome) values ('Leannon Inc');
insert into fornecedores (nome) values ('Harris, Johnston and Crooks');
insert into fornecedores (nome) values ('Orn-Murray');
insert into fornecedores (nome) values ('Hodkiewicz, Tromp and Hammes');
insert into fornecedores (nome) values ('Dare-Harber');
insert into fornecedores (nome) values ('Hintz Group');
insert into fornecedores (nome) values ('Conroy Inc');
insert into fornecedores (nome) values ('Lakin Group');
insert into fornecedores (nome) values ('Kreiger Inc');
insert into fornecedores (nome) values ('Renner-Hand');
insert into fornecedores (nome) values ('Mitchell-Deckow');
insert into fornecedores (nome) values ('Jacobs-Stoltenberg');
insert into fornecedores (nome) values ('Luettgen, Schaden and Sawayn');
insert into fornecedores (nome) values ('Nikolaus, Schinner and Durgan');
insert into fornecedores (nome) values ('Pfannerstill Group');
insert into fornecedores (nome) values ('Bauch-Pouros');
insert into fornecedores (nome) values ('Sawayn-Tremblay');
insert into fornecedores (nome) values ('Stroman, Russel and Cormier');
insert into fornecedores (nome) values ('Doyle-Hilpert');
insert into fornecedores (nome) values ('Kerluke Inc');
insert into fornecedores (nome) values ('Hoppe, Erdman and Yundt');
insert into fornecedores (nome) values ('Kshlerin LLC');
insert into fornecedores (nome) values ('Strosin, Hammes and MacGyver');
insert into fornecedores (nome) values ('Schmitt-Beier');
insert into fornecedores (nome) values ('Hoeger and Sons');
insert into fornecedores (nome) values ('Hirthe, Barton and Harvey');
insert into fornecedores (nome) values ('Koelpin-Davis');
insert into fornecedores (nome) values ('Crona-Graham');
insert into fornecedores (nome) values ('Mayer LLC');
insert into fornecedores (nome) values ('Walsh, Tromp and Moore');
insert into fornecedores (nome) values ('Wilderman-Goodwin');
insert into fornecedores (nome) values ('O''Connell Inc');
insert into fornecedores (nome) values ('Stanton-Mertz');
insert into fornecedores (nome) values ('Medhurst Inc');
insert into fornecedores (nome) values ('Kris, Bradtke and Kovacek');
insert into fornecedores (nome) values ('Smitham Group');
insert into fornecedores (nome) values ('Stanton LLC');
insert into fornecedores (nome) values ('Bradtke LLC');
insert into fornecedores (nome) values ('Gulgowski, Larson and Reichel');
insert into fornecedores (nome) values ('Konopelski, Kuhic and McClure');
insert into fornecedores (nome) values ('Howell, Collins and Hilll');
insert into fornecedores (nome) values ('Ortiz, Reichel and Pollich');
insert into fornecedores (nome) values ('Powlowski Inc');
insert into fornecedores (nome) values ('Schuster-Klocko');
insert into fornecedores (nome) values ('Jakubowski LLC');
insert into fornecedores (nome) values ('Aufderhar, Medhurst and Kilback');
insert into fornecedores (nome) values ('Greenfelder, Will and Quigley');
insert into fornecedores (nome) values ('Heathcote-Kub');
insert into fornecedores (nome) values ('Collier-Fay');
insert into fornecedores (nome) values ('Metz LLC');
insert into fornecedores (nome) values ('Fritsch-Schmitt');
insert into fornecedores (nome) values ('Lynch Group');
insert into fornecedores (nome) values ('Leannon LLC');
insert into fornecedores (nome) values ('Lehner, Brown and Harris');
insert into fornecedores (nome) values ('Schoen Group');
insert into fornecedores (nome) values ('Medhurst-Torp');
insert into fornecedores (nome) values ('Hartmann LLC');
insert into fornecedores (nome) values ('Sauer LLC');
insert into fornecedores (nome) values ('Moen, Friesen and Bradtke');
insert into fornecedores (nome) values ('King Group');
insert into fornecedores (nome) values ('Keeling, Jones and Klein');
insert into fornecedores (nome) values ('Adams-Abernathy');
insert into fornecedores (nome) values ('Schmidt-Feeney');
insert into fornecedores (nome) values ('Zboncak Inc');
insert into fornecedores (nome) values ('Frami-Littel');
insert into fornecedores (nome) values ('Mayer, Grant and Heaney');
insert into fornecedores (nome) values ('Hagenes and Sons');
insert into fornecedores (nome) values ('Osinski and Sons');
insert into fornecedores (nome) values ('Renner LLC');
insert into fornecedores (nome) values ('Vandervort-Bashirian');
insert into fornecedores (nome) values ('Rau Inc');
insert into fornecedores (nome) values ('Stamm and Sons');
insert into fornecedores (nome) values ('Powlowski-Hermiston');
insert into fornecedores (nome) values ('Marks-Breitenberg');
insert into fornecedores (nome) values ('Lubowitz, Ritchie and Heidenreich');
insert into fornecedores (nome) values ('Rowe, Fay and Gislason');
insert into fornecedores (nome) values ('Davis Inc');
insert into fornecedores (nome) values ('Boehm LLC');
insert into fornecedores (nome) values ('Bernhard LLC');
insert into fornecedores (nome) values ('VonRueden LLC');
insert into fornecedores (nome) values ('Bartell-Schmitt');
insert into fornecedores (nome) values ('Strosin-Bradtke');
insert into fornecedores (nome) values ('Thompson and Sons');
insert into fornecedores (nome) values ('Price and Sons');
insert into fornecedores (nome) values ('Stamm Group');
insert into fornecedores (nome) values ('Stark-Brekke');
insert into fornecedores (nome) values ('Gerhold, Kovacek and Christiansen');
insert into fornecedores (nome) values ('Ernser, Kuphal and Crooks');
insert into fornecedores (nome) values ('Brakus-Harber');
insert into fornecedores (nome) values ('Johns-Will');
insert into fornecedores (nome) values ('Trantow, Leffler and Schowalter');
insert into fornecedores (nome) values ('Treutel-Towne');
insert into fornecedores (nome) values ('Ward, Thiel and Yundt');
insert into fornecedores (nome) values ('Quigley LLC');
insert into fornecedores (nome) values ('Ortiz-Schmeler');
insert into fornecedores (nome) values ('Hirthe-Pagac');
insert into fornecedores (nome) values ('Runolfsson-Hyatt');
insert into fornecedores (nome) values ('Green LLC');
insert into fornecedores (nome) values ('Prohaska-Greenholt');
insert into fornecedores (nome) values ('Powlowski and Sons');
insert into fornecedores (nome) values ('Fay, Heathcote and Wisozk');
insert into fornecedores (nome) values ('Davis Group');
insert into fornecedores (nome) values ('Kling, Wisozk and Hermiston');
insert into fornecedores (nome) values ('Lynch, Haag and Daugherty');
insert into fornecedores (nome) values ('Kovacek and Sons');
insert into fornecedores (nome) values ('Bashirian-Emmerich');
insert into fornecedores (nome) values ('Schaden LLC');
insert into fornecedores (nome) values ('Wiza-Jacobson');
insert into fornecedores (nome) values ('Hilpert, Watsica and Nikolaus');
insert into fornecedores (nome) values ('Cummerata-Buckridge');
insert into fornecedores (nome) values ('Breitenberg, Muller and Pouros');
insert into fornecedores (nome) values ('Volkman-Prosacco');
insert into fornecedores (nome) values ('Gottlieb Inc');
insert into fornecedores (nome) values ('Sporer, Mraz and Schoen');
insert into fornecedores (nome) values ('Dicki Group');
insert into fornecedores (nome) values ('Morar-Moore');
insert into fornecedores (nome) values ('Kemmer, Wisoky and Bernier');
insert into fornecedores (nome) values ('Sipes LLC');
insert into fornecedores (nome) values ('Jenkins and Sons');
insert into fornecedores (nome) values ('Lindgren, Corkery and Skiles');
insert into fornecedores (nome) values ('Cummings Inc');
insert into fornecedores (nome) values ('Gutmann, Bode and Crist');
insert into fornecedores (nome) values ('Kub and Sons');
insert into fornecedores (nome) values ('King-Hyatt');
insert into fornecedores (nome) values ('Hagenes-Morissette');
insert into fornecedores (nome) values ('Cremin-Brakus');
insert into fornecedores (nome) values ('Hermann-Johnston');
insert into fornecedores (nome) values ('O''Hara Group');
insert into fornecedores (nome) values ('Heathcote-Walker');
insert into fornecedores (nome) values ('Howe, Cassin and Dickinson');
insert into fornecedores (nome) values ('Bergnaum and Sons');
insert into fornecedores (nome) values ('Morar LLC');
insert into fornecedores (nome) values ('VonRueden Group');
insert into fornecedores (nome) values ('Prosacco-Boyer');
insert into fornecedores (nome) values ('Schneider Inc');
insert into fornecedores (nome) values ('Gusikowski-Anderson');
insert into fornecedores (nome) values ('Hoeger and Sons');
insert into fornecedores (nome) values ('Ankunding, Klein and Hane');
insert into fornecedores (nome) values ('Beahan, Hintz and Feil');
insert into fornecedores (nome) values ('Skiles, Padberg and Reinger');
insert into fornecedores (nome) values ('Daniel Inc');
insert into fornecedores (nome) values ('Sanford, Barton and Raynor');
insert into fornecedores (nome) values ('Hirthe, Flatley and Rau');
insert into fornecedores (nome) values ('Hintz Group');
insert into fornecedores (nome) values ('Mosciski-Roob');
insert into fornecedores (nome) values ('Zulauf, Bogan and Strosin');
insert into fornecedores (nome) values ('Wuckert-Huel');
insert into fornecedores (nome) values ('Ortiz-Zulauf');
insert into fornecedores (nome) values ('Rutherford, Okuneva and Barton');
insert into fornecedores (nome) values ('Littel-Osinski');
insert into fornecedores (nome) values ('Conn-Ward');
insert into fornecedores (nome) values ('Morar-Barton');
insert into fornecedores (nome) values ('Crooks-Crooks');
insert into fornecedores (nome) values ('MacGyver-Bauch');
insert into fornecedores (nome) values ('Lebsack and Sons');
insert into fornecedores (nome) values ('Conroy and Sons');
insert into fornecedores (nome) values ('Murazik, Harber and Parisian');
insert into fornecedores (nome) values ('Baumbach, Rodriguez and Kreiger');
insert into fornecedores (nome) values ('Vandervort LLC');
insert into fornecedores (nome) values ('Zboncak-Schoen');
insert into fornecedores (nome) values ('Armstrong Inc');
insert into fornecedores (nome) values ('Kuhic Inc');
insert into fornecedores (nome) values ('Sporer, Batz and Lesch');
insert into fornecedores (nome) values ('Marks, Fay and Kuvalis');
insert into fornecedores (nome) values ('Rau, Johnston and Schamberger');
insert into fornecedores (nome) values ('Wiegand Group');
insert into fornecedores (nome) values ('Kutch-Hartmann');
insert into fornecedores (nome) values ('Smith-Ernser');
insert into fornecedores (nome) values ('Botsford Group');
insert into fornecedores (nome) values ('Grady LLC');
insert into fornecedores (nome) values ('Grant, Kihn and Feil');
insert into fornecedores (nome) values ('Conroy Inc');
insert into fornecedores (nome) values ('Macejkovic and Sons');
insert into fornecedores (nome) values ('Considine LLC');
insert into fornecedores (nome) values ('Hodkiewicz-Berge');
insert into fornecedores (nome) values ('Kiehn Group');
insert into fornecedores (nome) values ('Kessler-Schowalter');
insert into fornecedores (nome) values ('Gerhold, Haag and Hayes');
insert into fornecedores (nome) values ('Ward-Leffler');
insert into fornecedores (nome) values ('Treutel, Daugherty and Langworth');
insert into fornecedores (nome) values ('Hoeger and Sons');
insert into fornecedores (nome) values ('Davis Inc');
insert into fornecedores (nome) values ('Blanda LLC');
insert into fornecedores (nome) values ('Schaefer, Osinski and Bins');
insert into fornecedores (nome) values ('Bartoletti and Sons');
insert into fornecedores (nome) values ('Lynch Inc');
insert into fornecedores (nome) values ('Mayer, Roberts and Stoltenberg');
insert into fornecedores (nome) values ('Boyle, Dare and Cartwright');
insert into fornecedores (nome) values ('Purdy, Upton and Barton');
insert into fornecedores (nome) values ('Vandervort-Barrows');
insert into fornecedores (nome) values ('Brekke, Funk and Ondricka');
insert into fornecedores (nome) values ('D''Amore, Hudson and Reynolds');
insert into fornecedores (nome) values ('Lynch-Rolfson');
insert into fornecedores (nome) values ('Stoltenberg-Abernathy');
insert into fornecedores (nome) values ('McGlynn, Haley and Blanda');
insert into fornecedores (nome) values ('O''Connell Group');
insert into fornecedores (nome) values ('Langworth Inc');
insert into fornecedores (nome) values ('Muller-Rosenbaum');
insert into fornecedores (nome) values ('Robel, Block and Orn');
insert into fornecedores (nome) values ('Graham, Kreiger and Upton');
insert into fornecedores (nome) values ('Davis, Hodkiewicz and Feest');
insert into fornecedores (nome) values ('Carter, Lehner and Lockman');
insert into fornecedores (nome) values ('Barton and Sons');
insert into fornecedores (nome) values ('Marquardt, Bayer and Gorczany');
insert into fornecedores (nome) values ('Corwin-Pagac');
insert into fornecedores (nome) values ('Langosh, Tillman and Boyle');
insert into fornecedores (nome) values ('Robel LLC');
insert into fornecedores (nome) values ('Okuneva Inc');
insert into fornecedores (nome) values ('Adams-Rodriguez');
insert into fornecedores (nome) values ('Swift, Leuschke and Padberg');
insert into fornecedores (nome) values ('Ryan-Wisoky');
insert into fornecedores (nome) values ('Farrell, Bartell and Hoppe');
insert into fornecedores (nome) values ('Quitzon, Bechtelar and Weimann');
insert into fornecedores (nome) values ('Schiller-Heidenreich');
insert into fornecedores (nome) values ('McKenzie Inc');
insert into fornecedores (nome) values ('Greenfelder, Pfannerstill and Hilpert');
insert into fornecedores (nome) values ('Ebert, Heaney and Lehner');
insert into fornecedores (nome) values ('Conroy LLC');
insert into fornecedores (nome) values ('Kulas Group');
insert into fornecedores (nome) values ('Paucek-Bayer');
insert into fornecedores (nome) values ('Rice-Corwin');
insert into fornecedores (nome) values ('Welch-Moore');
insert into fornecedores (nome) values ('Lindgren, Rau and Sawayn');
insert into fornecedores (nome) values ('Monahan-Lind');
insert into fornecedores (nome) values ('Steuber and Sons');
insert into fornecedores (nome) values ('Ullrich Group');
insert into fornecedores (nome) values ('Bruen-Rau');
insert into fornecedores (nome) values ('Marks, Pfeffer and Beer');
insert into fornecedores (nome) values ('Hartmann-Huel');
insert into fornecedores (nome) values ('Johnson-Lynch');
insert into fornecedores (nome) values ('Stanton, Stoltenberg and Johnston');
insert into fornecedores (nome) values ('Leffler-Padberg');
insert into fornecedores (nome) values ('Orn-Rodriguez');
insert into fornecedores (nome) values ('Klocko, Dietrich and Dach');
insert into fornecedores (nome) values ('Rau, Lakin and Swift');
insert into fornecedores (nome) values ('Bechtelar and Sons');
insert into fornecedores (nome) values ('Kessler-Abshire');
insert into fornecedores (nome) values ('Mayer Inc');
insert into fornecedores (nome) values ('Schulist-Stracke');
insert into fornecedores (nome) values ('Monahan-Champlin');
insert into fornecedores (nome) values ('Ryan-Kuhn');
insert into fornecedores (nome) values ('Hills LLC');
insert into fornecedores (nome) values ('Rogahn-Swift');
insert into fornecedores (nome) values ('Padberg-Wunsch');
insert into fornecedores (nome) values ('Kutch-Schuppe');
insert into fornecedores (nome) values ('Haag and Sons');
insert into fornecedores (nome) values ('Langosh-Gorczany');
insert into fornecedores (nome) values ('Lubowitz-Quigley');
insert into fornecedores (nome) values ('Nicolas LLC');
insert into fornecedores (nome) values ('Walker, Zieme and McKenzie');
insert into fornecedores (nome) values ('Rodriguez-Jaskolski');
insert into fornecedores (nome) values ('Hirthe Inc');
insert into fornecedores (nome) values ('Hamill LLC');
insert into fornecedores (nome) values ('Rowe, Schneider and Swaniawski');
insert into fornecedores (nome) values ('Hodkiewicz, Rosenbaum and Vandervort');
insert into fornecedores (nome) values ('Hyatt-Nolan');
insert into fornecedores (nome) values ('Hand Group');
insert into fornecedores (nome) values ('Braun, Littel and Zemlak');
insert into fornecedores (nome) values ('Larson-Collier');
insert into fornecedores (nome) values ('Quitzon Group');
insert into fornecedores (nome) values ('Ratke, Hauck and Schmidt');
insert into fornecedores (nome) values ('Fay, Cummings and Schowalter');
insert into fornecedores (nome) values ('Koelpin-Morar');
insert into fornecedores (nome) values ('Bayer, Schiller and Gleichner');
insert into fornecedores (nome) values ('Murray-Zulauf');
insert into fornecedores (nome) values ('Boyer, Harvey and Rippin');
insert into fornecedores (nome) values ('Klocko LLC');
insert into fornecedores (nome) values ('Streich, Heaney and Reichert');
insert into fornecedores (nome) values ('Howell, Boehm and Hane');
insert into fornecedores (nome) values ('Braun, Moore and Hilll');
insert into fornecedores (nome) values ('Gerlach-Kassulke');
insert into fornecedores (nome) values ('Sauer, Kunze and Rodriguez');
insert into fornecedores (nome) values ('Anderson-Schiller');
insert into fornecedores (nome) values ('Ledner-Reichert');
insert into fornecedores (nome) values ('Lind, Hegmann and Heaney');
insert into fornecedores (nome) values ('Homenick Inc');
insert into fornecedores (nome) values ('Monahan Inc');
insert into fornecedores (nome) values ('Littel-Nitzsche');
insert into fornecedores (nome) values ('Becker-Wiza');
insert into fornecedores (nome) values ('Gutmann-Kuhn');
insert into fornecedores (nome) values ('Crooks LLC');
insert into fornecedores (nome) values ('Kshlerin-McClure');
insert into fornecedores (nome) values ('Hammes-King');
insert into fornecedores (nome) values ('Lesch, Pagac and Harber');
insert into fornecedores (nome) values ('Ullrich-Hoppe');
insert into fornecedores (nome) values ('Lowe, Mohr and Thiel');
insert into fornecedores (nome) values ('Kutch and Sons');
insert into fornecedores (nome) values ('Lind Group');
insert into fornecedores (nome) values ('Altenwerth, Wilderman and Boyer');
insert into fornecedores (nome) values ('Rath, Stokes and Wolff');
insert into fornecedores (nome) values ('Wisozk-Reichel');
insert into fornecedores (nome) values ('Schneider, Larkin and Feil');
insert into fornecedores (nome) values ('Kuphal-Berge');
insert into fornecedores (nome) values ('Waters Inc');
insert into fornecedores (nome) values ('Green, Bins and Barrows');
insert into fornecedores (nome) values ('Parker, Streich and Koch');
insert into fornecedores (nome) values ('Pfeffer, Bailey and Schmitt');
insert into fornecedores (nome) values ('Macejkovic, Schoen and Cremin');
insert into fornecedores (nome) values ('Miller, Hilpert and Kunze');
insert into fornecedores (nome) values ('Muller, Koss and Roob');
insert into fornecedores (nome) values ('Rice-Reilly');
insert into fornecedores (nome) values ('Muller-Windler');
insert into fornecedores (nome) values ('Jaskolski Group');
insert into fornecedores (nome) values ('Hodkiewicz, Wisoky and West');
insert into fornecedores (nome) values ('Tromp LLC');
insert into fornecedores (nome) values ('Wunsch, Medhurst and Wisoky');
insert into fornecedores (nome) values ('Shanahan, Gusikowski and Fritsch');
insert into fornecedores (nome) values ('Nienow, Ferry and Reynolds');
insert into fornecedores (nome) values ('Welch Inc');
insert into fornecedores (nome) values ('Graham, Moore and Littel');
insert into fornecedores (nome) values ('Ratke-Rodriguez');
insert into fornecedores (nome) values ('Kassulke-Boehm');
insert into fornecedores (nome) values ('Schimmel-Morissette');
insert into fornecedores (nome) values ('Schinner, Considine and Schroeder');
insert into fornecedores (nome) values ('Daugherty and Sons');
insert into fornecedores (nome) values ('McDermott, Ward and Herzog');
insert into fornecedores (nome) values ('Haley and Sons');
insert into fornecedores (nome) values ('Leffler Inc');
insert into fornecedores (nome) values ('Lemke LLC');
insert into fornecedores (nome) values ('Hansen LLC');
insert into fornecedores (nome) values ('Daugherty Group');
insert into fornecedores (nome) values ('Cummerata-Lakin');
insert into fornecedores (nome) values ('Hamill and Sons');
insert into fornecedores (nome) values ('Murazik, Schroeder and Christiansen');
insert into fornecedores (nome) values ('Bartoletti, Gorczany and Lubowitz');
insert into fornecedores (nome) values ('McKenzie Inc');
insert into fornecedores (nome) values ('Hegmann LLC');
insert into fornecedores (nome) values ('Romaguera Group');
insert into fornecedores (nome) values ('Doyle Inc');
insert into fornecedores (nome) values ('Baumbach and Sons');
insert into fornecedores (nome) values ('Cummerata-Bartoletti');
insert into fornecedores (nome) values ('Toy-O''Conner');
insert into fornecedores (nome) values ('Fadel and Sons');
insert into fornecedores (nome) values ('Nicolas, Hayes and Krajcik');
insert into fornecedores (nome) values ('Leffler, Lebsack and Casper');
insert into fornecedores (nome) values ('Schuster Inc');
insert into fornecedores (nome) values ('Brakus-Thiel');
insert into fornecedores (nome) values ('Mitchell-Kiehn');
insert into fornecedores (nome) values ('Schuster, Harris and Trantow');
insert into fornecedores (nome) values ('Mohr, Fisher and Homenick');
insert into fornecedores (nome) values ('Langosh-Deckow');
insert into fornecedores (nome) values ('Wilkinson-Simonis');
insert into fornecedores (nome) values ('Smith-Hegmann');
insert into fornecedores (nome) values ('Langworth LLC');
insert into fornecedores (nome) values ('Mueller, Mueller and Bernier');
insert into fornecedores (nome) values ('Goyette-Nader');
insert into fornecedores (nome) values ('Schimmel-Weimann');
insert into fornecedores (nome) values ('Kohler-Denesik');
insert into fornecedores (nome) values ('Denesik and Sons');
insert into fornecedores (nome) values ('Walsh Inc');
insert into fornecedores (nome) values ('Hoppe and Sons');
insert into fornecedores (nome) values ('Blick, Casper and Rohan');
insert into fornecedores (nome) values ('Spinka Inc');
insert into fornecedores (nome) values ('Mante Group');
insert into fornecedores (nome) values ('Hegmann and Sons');
insert into fornecedores (nome) values ('Kuhn, Borer and Oberbrunner');
insert into fornecedores (nome) values ('Stokes-Robel');
insert into fornecedores (nome) values ('Erdman and Sons');
insert into fornecedores (nome) values ('Auer-Pfannerstill');
insert into fornecedores (nome) values ('Daugherty, Murphy and Ledner');
insert into fornecedores (nome) values ('Little-Miller');
insert into fornecedores (nome) values ('Casper-Schoen');
insert into fornecedores (nome) values ('Bahringer Inc');
insert into fornecedores (nome) values ('Denesik and Sons');
insert into fornecedores (nome) values ('Kertzmann-Schinner');
insert into fornecedores (nome) values ('Willms, Little and Halvorson');
insert into fornecedores (nome) values ('Dare-Little');
insert into fornecedores (nome) values ('Bruen, Dach and Wyman');
insert into fornecedores (nome) values ('Abernathy and Sons');
insert into fornecedores (nome) values ('Powlowski, King and Volkman');
insert into fornecedores (nome) values ('Bailey-Morissette');
insert into fornecedores (nome) values ('Kilback-Smith');
insert into fornecedores (nome) values ('Mayer, Smith and Jenkins');
insert into fornecedores (nome) values ('Fadel and Sons');
insert into fornecedores (nome) values ('Bauch-Lind');
insert into fornecedores (nome) values ('Hamill Inc');
insert into fornecedores (nome) values ('Runte-Blanda');
insert into fornecedores (nome) values ('Streich-Lakin');
insert into fornecedores (nome) values ('Predovic-Denesik');
insert into fornecedores (nome) values ('Windler and Sons');
insert into fornecedores (nome) values ('Muller Group');
insert into fornecedores (nome) values ('Weissnat, Bernhard and Schumm');
insert into fornecedores (nome) values ('Denesik, Hintz and Ruecker');
insert into fornecedores (nome) values ('Adams Inc');
insert into fornecedores (nome) values ('Krajcik-Bernier');
insert into fornecedores (nome) values ('Sauer, Conn and Schinner');
insert into fornecedores (nome) values ('Tromp Group');
insert into fornecedores (nome) values ('Bradtke, Hagenes and Pfeffer');
insert into fornecedores (nome) values ('Corwin, Osinski and Langworth');
insert into fornecedores (nome) values ('Hackett-Luettgen');
insert into fornecedores (nome) values ('Weissnat-Connelly');
insert into fornecedores (nome) values ('Lynch-Tremblay');
insert into fornecedores (nome) values ('Powlowski, Gerlach and Barton');
insert into fornecedores (nome) values ('Parisian-Klein');
insert into fornecedores (nome) values ('Olson-Langworth');
insert into fornecedores (nome) values ('Schaefer-Lemke');
insert into fornecedores (nome) values ('Gleason, Farrell and Greenfelder');
insert into fornecedores (nome) values ('Conroy and Sons');
insert into fornecedores (nome) values ('Hayes, Sauer and King');
insert into fornecedores (nome) values ('Berge, Veum and Hayes');
insert into fornecedores (nome) values ('Legros-Sporer');
insert into fornecedores (nome) values ('Gottlieb LLC');
insert into fornecedores (nome) values ('Kulas Inc');
insert into fornecedores (nome) values ('Krajcik-Weimann');
insert into fornecedores (nome) values ('Grant-Fay');
insert into fornecedores (nome) values ('Steuber, Leuschke and McKenzie');
insert into fornecedores (nome) values ('Ferry, Wolff and Roberts');
insert into fornecedores (nome) values ('Weissnat-Huel');
insert into fornecedores (nome) values ('Ankunding-Crona');
insert into fornecedores (nome) values ('Kemmer Inc');
insert into fornecedores (nome) values ('Wolff-Leffler');
insert into fornecedores (nome) values ('Von-Renner');
insert into fornecedores (nome) values ('Buckridge, Bins and Miller');
